{{- if .Values.pint.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pint.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pint.labels" . | nindent 4 }}
data:
  PINT_CLIENT_ID:          {{ .Values.config.clientID | quote }}
  PINT_SERVER_URL:         {{ .Values.config.serverURL | quote }}
  PINT_IPA_HOST:           {{ .Values.config.ipaHost | quote }}
  PINT_IPA_SERVICE_ACCOUNT: {{ .Values.config.ipaServiceAccount | quote }}
  PINT_IPA_CA_NAME:        {{ .Values.config.ipaCAName | quote }}
  PINT_IPA_RADSEC_CA_NAME: {{ .Values.config.ipaRadSecCAName | quote }}
  PINT_IPA_ROOT_CA_NAME:   {{ .Values.config.ipaRootCAName | quote }}
  PINT_WIFI_SSID:          {{ .Values.config.wifiSSID | quote }}
  PINT_RADIUS_SERVER:      {{ .Values.config.radiusServer | quote }}
  {{- if .Values.config.ipaCertProfile }}
  PINT_IPA_CERT_PROFILE:                    {{ .Values.config.ipaCertProfile | quote }}
  {{- end }}
  {{- if .Values.config.ipaRadSecClientCertProfile }}
  PINT_IPA_RADSEC_CLIENT_CERT_PROFILE:      {{ .Values.config.ipaRadSecClientCertProfile | quote }}
  {{- end }}
  {{- if .Values.config.ipaRadSecServerCertProfile }}
  PINT_IPA_RADSEC_SERVER_CERT_PROFILE:      {{ .Values.config.ipaRadSecServerCertProfile | quote }}
  {{- end }}
  {{- if .Values.config.ipaSkipTLSVerify }}
  PINT_IPA_SKIP_TLS_VERIFY: "true"
  {{- end }}
{{- end }}
