{{- if .Values.pint.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pint.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pint.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "pint.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "pint.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "pint.serviceAccountName" . }}
      containers:
        - name: pint
          image: {{ include "pint.image" . }}
          imagePullPolicy: {{ .Values.pint.image.pullPolicy }}
          ports:
            - containerPort: 8080
              name: http
          envFrom:
            - secretRef:
                name: {{ include "pint.envSecret" . }}
          env:
            - name: PINT_CLIENT_ID
              value: {{ .Values.config.clientID | quote }}
            - name: PINT_SERVER_URL
              value: {{ .Values.config.serverURL | quote }}
            - name: PINT_IPA_HOST
              value: {{ .Values.config.ipaHost | quote }}
            - name: PINT_IPA_SERVICE_ACCOUNT
              value: {{ .Values.config.ipaServiceAccount | quote }}
            - name: PINT_IPA_WIRELESS_CA_NAME
              value: {{ .Values.config.ipaWirelessCAName | quote }}
            - name: PINT_IPA_RADSEC_CA_NAME
              value: {{ .Values.config.ipaRadSecCAName | quote }}
            - name: PINT_IPA_ROOT_CA_NAME
              value: {{ .Values.config.ipaRootCAName | quote }}
            - name: PINT_WIFI_SSID
              value: {{ .Values.config.wifiSSID | quote }}
            - name: PINT_RADIUS_SERVER
              value: {{ .Values.config.radiusServer | quote }}
            {{- if .Values.config.ipaCertProfile }}
            - name: PINT_IPA_CERT_PROFILE
              value: {{ .Values.config.ipaCertProfile | quote }}
            {{- end }}
            {{- if .Values.config.ipaRadSecClientCertProfile }}
            - name: PINT_IPA_RADSEC_CLIENT_CERT_PROFILE
              value: {{ .Values.config.ipaRadSecClientCertProfile | quote }}
            {{- end }}
            {{- if .Values.config.ipaRadSecServerCertProfile }}
            - name: PINT_IPA_RADSEC_SERVER_CERT_PROFILE
              value: {{ .Values.config.ipaRadSecServerCertProfile | quote }}
            {{- end }}
            {{- if .Values.config.ipaSkipTLSVerify }}
            - name: PINT_IPA_SKIP_TLS_VERIFY
              value: "true"
            {{- end }}
            {{- if not .Values.config.radSecCheckCRL }}
            - name: PINT_RADIUS_RADSEC_CHECK_CRL
              value: "false"
            {{- end }}
            {{- if .Values.config.radSecProxyProtocol }}
            - name: PINT_RADIUS_RADSEC_PROXY_PROTOCOL
              value: "true"
            {{- end }}
            {{- if .Values.config.radSecStatusPort }}
            - name: PINT_RADIUS_STATUS_PORT
              value: {{ .Values.config.radSecStatusPort | quote }}
            {{- end }}
            {{- if .Values.config.radSecStatusAddr }}
            - name: PINT_RADIUS_STATUS_ADDR
              value: {{ .Values.config.radSecStatusAddr | quote }}
            {{- end }}
            {{- if .Values.config.codeSigningCAName }}
            - name: PINT_IPA_CODE_SIGNING_CA_NAME
              value: {{ .Values.config.codeSigningCAName | quote }}
            - name: PINT_PROFILE_SIGNING_CERT_SECRET
              value: {{ include "pint.secretName.profileSigningCert" . | quote }}
            {{- if .Values.config.codeSigningCertProfile }}
            - name: PINT_IPA_CODE_SIGNING_CERT_PROFILE
              value: {{ .Values.config.codeSigningCertProfile | quote }}
            {{- end }}
            {{- end }}
            - name: PINT_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: PINT_CONFIG_SECRET
              value: {{ include "pint.secretName.config" . | quote }}
            - name: PINT_RADSEC_CERT_SECRET
              value: {{ include "pint.secretName.radSecCert" . | quote }}
            {{- if .Values.freeradius.enabled }}
            - name: PINT_FREERADIUS_DEPLOYMENT
              value: {{ include "pint.freeradiusFullname" . | quote }}
            {{- end }}
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
{{- end }}
