{{- if .Values.freeradius.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pint.freeradiusFullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pint.freeradiusLabels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "pint.freeradiusSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "pint.freeradiusLabels" . | nindent 8 }}
    spec:
      containers:
        - name: freeradius
          image: {{ include "pint.freeradiusImage" . }}
          imagePullPolicy: {{ .Values.freeradius.image.pullPolicy }}
          ports:
            - containerPort: 2083
              name: radsec
            {{- if .Values.freeradius.statusServer.enabled }}
            - containerPort: 18121
              name: status
              protocol: UDP
            {{- end }}
          securityContext:
            {{- toYaml .Values.freeradius.securityContext | nindent 12 }}
          volumeMounts:
            - name: pint-config
              mountPath: /etc/pint/config
              readOnly: true
            - name: pint-radsec
              mountPath: /etc/pint/radsec
              readOnly: true
      volumes:
        - name: pint-config
          secret:
            secretName: {{ include "pint.secretName.config" . }}
            optional: true
        - name: pint-radsec
          projected:
            defaultMode: 0444
            sources:
              - secret:
                  name: {{ include "pint.secretName.radSecCert" . }}
                  optional: true
              - secret:
                  name: {{ include "pint.secretName.eapCert" . }}
                  optional: true
{{- end }}
