{{- if and .Values.freeradius.enabled .Values.freeradius.statusServer.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pint.freeradiusFullname" . }}-status-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pint.freeradiusLabels" . | nindent 4 }}
type: Opaque
data:
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace (printf "%s-status-secret" (include "pint.freeradiusFullname" .))) | default dict }}
  {{- $secretData := (index $secretObj "data") | default dict }}
  {{- $secret := (index $secretData "status-secret") | default (randAlphaNum 32 | b64enc) }}
  status-secret: {{ $secret | quote }}
{{- end }}
