{{- if .Values.freeradius.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pint.freeradiusFullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pint.freeradiusLabels" . | nindent 4 }}
  {{- if .Values.openshift.build.enabled }}
  annotations:
    image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"{{ .Values.openshift.build.freeradiusImageStreamName }}:{{ .Values.freeradius.image.tag }}","namespace":"{{ .Release.Namespace }}"},"fieldPath":"spec.template.spec.containers[?(@.name==\"freeradius\")].image","paused":"false"}]'
  {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "pint.freeradiusSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "pint.freeradiusLabels" . | nindent 8 }}
    spec:
      containers:
        - name: freeradius
          image: {{ include "pint.freeradiusImage" . }}
          imagePullPolicy: {{ .Values.freeradius.image.pullPolicy }}
          ports:
            - containerPort: 2083
              name: radsec
            {{- if .Values.freeradius.statusServer.enabled }}
            - containerPort: 18121
              name: status
              protocol: UDP
            {{- end }}
          securityContext:
            {{- toYaml .Values.freeradius.securityContext | nindent 12 }}
          volumeMounts:
            - name: pint-config
              mountPath: /etc/pint/config
              readOnly: true
            - name: pint-radsec
              mountPath: /etc/pint/radsec
              readOnly: true
            - name: pint-eap
              mountPath: /etc/pint/eap
              readOnly: true
        {{- if .Values.freeradius.agentCheck.enabled }}
        - name: radsec-agent
          image: {{ include "pint.image" . }}
          imagePullPolicy: {{ .Values.pint.image.pullPolicy }}
          command: ["./radsec-agent"]
          args:
            - -listen=:{{ .Values.freeradius.agentCheck.port }}
            - -status=127.0.0.1:18121
            - -secret-file=/etc/pint/config/status-secret
          ports:
            - containerPort: {{ .Values.freeradius.agentCheck.port }}
              name: agent-check
          securityContext:
            {{- toYaml .Values.freeradius.securityContext | nindent 12 }}
          volumeMounts:
            - name: pint-config
              mountPath: /etc/pint/config
              readOnly: true
        {{- end }}
      volumes:
        - name: pint-config
          secret:
            secretName: {{ include "pint.secretName.config" . }}
            optional: true
        - name: pint-radsec
          secret:
            secretName: {{ include "pint.secretName.radSecCert" . }}
            defaultMode: 0444
            optional: true
        - name: pint-eap
          secret:
            secretName: {{ include "pint.secretName.eapCert" . }}
            defaultMode: 0444
            optional: true
{{- end }}
