{{- if and .Values.openshift.build.enabled .Values.openshift.build.manageImageStream }}
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: {{ .Values.openshift.build.imageStreamName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pint.labels" . | nindent 4 }}
spec:
  lookupPolicy:
    local: true
{{- if .Values.freeradius.enabled }}
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: {{ .Values.openshift.build.freeradiusImageStreamName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pint.freeradiusLabels" . | nindent 4 }}
spec:
  lookupPolicy:
    local: true
{{- end }}
{{- end }}
