// internal/radius/config_test.go
package radius_test

import (
	"strings"
	"testing"

	"github.com/ComputerScienceHouse/pint/internal/radius"
)

func TestRenderClientsConf_WithIP(t *testing.T) {
	ip := "192.168.1.0/24"
	clients := []radius.RadiusClient{
		{Username: "mbillow", IPCIDR: &ip},
	}
	out := radius.RenderClientsConf(clients)

	if !strings.Contains(out, "client mbillow_home") {
		t.Error("missing client block header")
	}
	if !strings.Contains(out, "ipaddr         = 192.168.1.0/24") {
		t.Error("missing ipaddr")
	}
	if !strings.Contains(out, "secret         = radsec") {
		t.Error("missing radsec secret")
	}
	if !strings.Contains(out, "proto          = tls") {
		t.Error("missing proto = tls (required for RadSec)")
	}
	if !strings.Contains(out, "shortname      = mbillow-home") {
		t.Error("missing shortname")
	}
	if !strings.Contains(out, "virtual_server = radsec") {
		t.Error("missing virtual_server = radsec (required for RadSec routing)")
	}
}

func TestRenderClientsConf_NoIP(t *testing.T) {
	clients := []radius.RadiusClient{
		{Username: "jsmith", IPCIDR: nil},
	}
	out := radius.RenderClientsConf(clients)

	if !strings.Contains(out, "ipaddr         = 0.0.0.0/0") {
		t.Error("missing wildcard ipaddr for nil IPCIDR")
	}
}

func TestRenderClientsConf_MultipleClients(t *testing.T) {
	ip := "10.0.0.0/8"
	clients := []radius.RadiusClient{
		{Username: "alice", IPCIDR: &ip},
		{Username: "bob", IPCIDR: nil},
	}
	out := radius.RenderClientsConf(clients)

	if !strings.Contains(out, "client alice_home") {
		t.Error("missing alice block")
	}
	if !strings.Contains(out, "client bob_home") {
		t.Error("missing bob block")
	}
}

func TestRenderClientsConf_Empty(t *testing.T) {
	out := radius.RenderClientsConf(nil)
	if !strings.Contains(out, "Auto-generated by PINT") {
		t.Error("missing header comment")
	}
}
