// internal/radius/config.go
package radius

import (
	"fmt"
	"strings"
)

// RenderClientsConf generates the FreeRADIUS clients.conf content from the given client list.
// Each client block includes proto = tls for RadSec (RFC 6614) support.
func RenderClientsConf(clients []RadiusClient) string {
	var b strings.Builder
	b.WriteString("# Auto-generated by PINT — do not edit manually\n\n")

	for _, c := range clients {
		ipaddr := "0.0.0.0/0"
		if c.IPCIDR != nil {
			ipaddr = *c.IPCIDR
		}
		fmt.Fprintf(&b, "client %s_home {\n", c.Username)
		fmt.Fprintf(&b, "    ipaddr    = %s\n", ipaddr)
		fmt.Fprintf(&b, "    secret    = %s\n", c.Secret)
		fmt.Fprintf(&b, "    proto     = tls\n")
		fmt.Fprintf(&b, "    shortname = %s-home\n", c.Username)
		b.WriteString("}\n\n")
	}
	return b.String()
}
