// internal/radius/config.go
package radius

import (
	"fmt"
	"regexp"
	"strings"
)

var safeUsername = regexp.MustCompile(`^[a-zA-Z0-9_-]+$`)

// RenderRadSecTLS generates the FreeRADIUS tls{} block for the RadSec listener.
// The output is written to the K8s config secret as radsec-tls.conf and
// $INCLUDE'd by the radsec virtual server so check_crl is env-var driven.
func RenderRadSecTLS(checkCRL bool) string {
	crl := "no"
	if checkCRL {
		crl = "yes"
	}
	return fmt.Sprintf(`# Auto-generated by PINT - do not edit manually
tls {
    private_key_file  = /etc/pint/radsec/tls.key
    certificate_file  = /etc/pint/radsec/tls.crt
    ca_file           = /etc/pint/radsec/ca.pem
    tls_min_version   = "1.2"
    cipher_list       = "ECDHE+AESGCM:DHE+AESGCM"
    ecdh_curve        = "secp384r1"

    verify {
        client_cert_ok = yes
        check_crl      = %s
    }
}
`, crl)
}

// RenderClientsConf generates the FreeRADIUS clients.conf content from the given client list.
// Each client block includes proto = tls for RadSec (RFC 6614) support.
func RenderClientsConf(clients []RadiusClient) string {
	var b strings.Builder
	b.WriteString("# Auto-generated by PINT - do not edit manually\n\n")

	for _, c := range clients {
		if !safeUsername.MatchString(c.Username) {
			continue
		}
		ipaddr := "0.0.0.0/0"
		if c.IPCIDR != nil {
			ipaddr = *c.IPCIDR
		}
		fmt.Fprintf(&b, "client %s_home {\n", c.Username)
		fmt.Fprintf(&b, "    ipaddr         = %s\n", ipaddr)
		b.WriteString("    secret         = radsec\n")
		b.WriteString("    proto          = tls\n")
		fmt.Fprintf(&b, "    shortname      = %s-home\n", c.Username)
		b.WriteString("    virtual_server = radsec\n")
		b.WriteString("}\n\n")
	}
	return b.String()
}
