apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pint
  namespace: pint
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["pint-radius-clients", "pint-radius-config", "pint-radsec-server"]
    verbs: ["get", "create", "update"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pint
  namespace: pint
subjects:
  - kind: ServiceAccount
    name: pint
    namespace: pint
roleRef:
  kind: Role
  name: pint
  apiGroup: rbac.authorization.k8s.io
